image: node:8

variables:
  HUGO_VERSION: '0.25.1'
  HUGO_SHA: 'fbf8ca850aaaaad331f5b40bbbe8e797115dab296a8486a53c0561f253ca7b00'

cache:
  untracked: true
  key: "$CI_BUILD_REF_NAME"
  paths:
    - node_modules/
    - tools/hugo-${HUGO_VERSION}.tar.gz

before_script:
  - apt-get install -y git
  - rm -rf public
  - npm install
  - bash scripts/install_tools.sh

stages:
  - build

build_data:
  stage: build
  script:
    - mkdir -p data
    - npm run build_poicount
    - npm run build_contributors
    - npm run build_breadcrumbs
    - npm run build_history
    - ./node_modules/.bin/gulp prod
    - npm run webpack
    - ./tools/hugo
  artifacts:
    paths:
      - ./public/./
    expire_in: 1 week

