image: node:8-slim

cache:
  untracked: true
  key: "$CI_BUILD_REF_NAME"
  paths:
    - node_modules/

before_script:
  - npm install

stages:
  - build

build_data:
  stage: build
  script:
    - mkdir -p data
    - npm run build_poicount
    - npm run build_contributors
