image: node:8-slim

before_script:
  - npm install
  - mkdir -p data

stages:
  - build

build_poicount:
  stage: build
  script:
    - npm run build_poicount

build_contributors:
  stage: build
  script:
    - npm run build_contributors
