baseURL = "https://www.strangenewplaces.org/"
languageCode = "en-us"
title = "StrangeNewPlaces"
metaDataFormat = "yaml"
editor = "em -n"
ignoreFiles = [ "\\.\\#" ]
disableKinds = []
[[menu.footer]]
    name = "Feedback"
    url = "https://gitlab.com/strangenewplaces/website/issues"
    weight = -1
    pre = "<i class='fa fa-comment'></i> "
